name: Build and Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-docker:
    name: 🐳 Build Docker Image
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm64/v8 ]
        include:
          - platform: linux/amd64
            runner: blacksmith-2vcpu-ubuntu-2404
          - platform: linux/arm64/v8
            runner: blacksmith-2vcpu-ubuntu-2404-arm
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Blacksmith
        uses: useblacksmith/setup-docker-builder@v1

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push for ${{ matrix.platform }}
        uses: useblacksmith/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/overmail/overmail-backend:latest-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
          platforms: ${{ matrix.platform }}

  merge-manifests:
    needs: build-docker
    runs-on: blacksmith
    name: 🛠️ Merge Docker Images
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          docker buildx imagetools create \
            -t ghcr.io/overmail/overmail-backend:latest \
            ghcr.io/overmail/overmail-backend:latest-amd64 \
            ghcr.io/overmail/overmail-backend:latest-arm64

  dependency-submission:
    name: 📊 Submit Dependency Graph
    runs-on: blacksmith-2vcpu-ubuntu-2404
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Restore Gradle cache
        id: restore-gradle-cache
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.versions.toml', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 24
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4