name: Build and Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-application:
    name: 🔨 Build and Deploy ${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout Code
          uses: actions/checkout@v4
      -   name: Restore Gradle cache
          id: restore-gradle-cache
          uses: actions/cache/restore@v4
          with:
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.versions.toml', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
      -   name: Set up JDK 24
          uses: actions/setup-java@v4
          with:
            java-version: '24'
            distribution: 'temurin'
      -   name: Build with Gradle
          run: ./gradlew buildFatJar --no-daemon
      -   name: Rename Artifact
          run: mv "$(ls -1 build/libs/*-all.jar | head -n 1)" app.jar
      -   name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: application
            path: app.jar
      -   name: Save Gradle cache
          uses: actions/cache/save@v4
          if: steps.restore-gradle-cache.outputs.cache-hit != 'true'
          with:
            key: ${{ steps.restore-gradle-cache.outputs.cache-primary-key }}
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
  build-docker:
    name: 🐳 Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - build-application
    steps:
      -   name: Checkout Code
          uses: actions/checkout@v4
      -   name: Download Artifact
          uses: actions/download-artifact@v4
          with:
            name: application
      -   name: Set up QEMU
          uses: docker/setup-qemu-action@v3

      -   name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

      -   name: Log in to GHCR
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      -   name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            context: .
            file: Dockerfile
            tags: ghcr.io/overmail/overmail-backend:latest
            platforms: linux/amd64,linux/arm64/v8

  dependency-submission:
    name: 📊 Submit Dependency Graph
    runs-on: ubuntu-latest
    needs: build-application
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    steps:
      -   name: Checkout sources
          uses: actions/checkout@v4
      -   name: Restore Gradle cache
          id: restore-gradle-cache
          uses: actions/cache/restore@v4
          with:
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.versions.toml', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
      -   name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: 23
      -   name: Generate and submit dependency graph
          uses: gradle/actions/dependency-submission@v4